### ISSUE TITLE
Media Gallery shows in wrong place in Moodle 3

### ISSUE THREAD

**Issue by stopfstedt** [kaltura/moodle-local_kalturamediagallery#1]
Hi,
We're in the process of upgrading to Moodle 3.2 and noticed that the Media Gallery appears in the now-defunct "Current Course" section of the navigation block (we're using a Clean-theme based custom theme, and intend to do so for the foreseeable future).

![selection_254](https://cloud.githubusercontent.com/assets/1410427/26018913/babc6168-3726-11e7-9034-dd25c078f91a.png)

Instead the link should appear underneath with the currently active course within the "My courses" or "Courses" sections:

![selection_253](https://cloud.githubusercontent.com/assets/1410427/26018920/c443264a-3726-11e7-980e-ee36cfe0ec49.png)

![selection_252](https://cloud.githubusercontent.com/assets/1410427/26018925/cbac5ea6-3726-11e7-88ee-cd27675b35a4.png)

**Comment by kaltura-hooks** [comment]
Hi @stopfstedt,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by stopfstedt** [comment]
- Plugin version is 2016122232, release is 'Kaltura release 4.0.11'.
- Moodle version is 2016120503.02, release '3.2.3+ (Build: 20170509)'

**Comment by stopfstedt** [comment]
superseded by https://github.com/kaltura/moodle_plugin/issues/137
